### ISSUE TITLE
[BUG] - Moulinette dropdown fields hardly readable in WFRP4e

### ISSUE THREAD

**Issue by Berytak** [SvenWerlen/moulinette-core#60]
**Describe the bug**
Content in dropdown menus are very hard to read due to white font color.

**Expected behavior**
To make it more readable the field or font colour should be changed for WFRP4e

**Screenshots**
![Formating_Moulinette](https://user-images.githubusercontent.com/85394657/215978974-28be83c5-5e14-40d4-b70b-868df52cd72a.jpg)

**Setup:**

Foundry Version: 10.291
System Version: Warhammer Fantasy Roleplay 4th Edition 6.3.1
Moulinette Core Version: 10.5.0
Browser & version: every browser and version

**Comment by SvenWerlen** [comment]
Sorry for the very long delay on this.
I can reproduce it with auto-scrolling. It is due to some incompatibility between Moulinette and WFRP4e styles. However, in the most recent releases, the selected entry is readable. 
![image](https://github.com/SvenWerlen/moulinette-core/assets/938060/370a60d1-e6ef-4b57-90d2-229671e26e8a)

Alternatively, you can switch "Auto-scrolling" (moulinette option) off. 
Let me know if this is still an issue.

**Comment by Berytak** [comment]
Looks good! The only thing not readable is the bottom bar that refers to the moulinette cloud. But that's not a big issue to me, as long as I can read the upper stuff.
Thanks mate!

![image](https://github.com/SvenWerlen/moulinette-core/assets/85394657/bf6ebd73-b69f-46b2-ab40-2b4b2b297e63)

**Comment by SvenWerlen** [comment]
Excellent. I fixed the issue with the bottom bar. I won't do a release just for it but it will be available as part of the next release.
