### ISSUE TITLE
Indexing doesn't work when folder name includes a "."

### ISSUE THREAD

**Issue by SvenWerlen** [SvenWerlen/moulinette-core#61]
Not sure this is the right place for this- if there is a period "." in a Folder Name, Indexing goes into an infinite loop 
Moulinette FileUtil | Assets: scanning moulinette/tiles/custom/Maps/Underground Dungeon/InfinityDungeon_2.2 ...  moulinette-file-util.js:443 
Moulinette FileUtil | Assets: 0 assets found    moulinette-file-util.js:445 
Moulinette FileUtil | Assets: 0 assets kepts after filtering   moulinette-file-util.js:434 
then repeats starting with 
Moulinette FileUtil | Assets: scanning moulinette/tiles/custom/Maps/Underground Dungeon/InfinityDungeon_2.2 ...

**Comment by LukeAbby** [comment]
The period makes it look like a file. It's a core Foundry bug: https://github.com/foundryvtt/foundryvtt/issues/8935. It will be fixed in V11 but can be patched fairly easily in the meantime.

The issue I opened goes into great detail but one thing I didn't mention this in the initial issue because it was already long was that it seems that ultimately `aws-sdk` misguidedly tries its best to match the behaviour of `ls` as you can see:
```bash
> touch foo
> ls foo
foo
> rm foo
> mkdir foo
> ls foo
[empty]
> touch foo/bar
> ls foo
bar
> rm -r foo
```
When you have just a file `ls` just echos the file's name.

Now we don't have a "file" conceptually but `aws-sdk` is really just guessing if something is a "file" or "folder" since S3 only has what it calls objects. Because it judges off of an "extension" this causes `a/b/c.d` to echo `a/b/c.d` and this ends up making it try to traverse into, well, `a/b/c.d` ad infinitum.

**Comment by SvenWerlen** [comment]
Wow, this is a very detailed explanation of the issue. Thank you, I appreciate. 
I'll then wait and check it on V11.

**Comment by SvenWerlen** [comment]
Would you mind confirming that the issue is fixed in V11? (I would then close this issue)

**Comment by SvenWerlen** [comment]
Tested on V11. Works as expected.
