### ISSUE TITLE
BUG - In Foundry Version 11, Moulinette will not show scenes from modules in the scenes tab

### ISSUE THREAD

**Issue by ktesterman007** [SvenWerlen/moulinette-core#65]
I have been using Moulinette for some time, and I have a lot of scenes from different patreon modules.  However, when upgrading to Foundry V11, Moulinette no longer shows any scenes from my local modules, I now only see cloud assets.  I tried disabling every module except the Moulinette modules and my scenes module, but still no difference, Moulinette only shows the cloud modules.

**Comment by SvenWerlen** [comment]
Thank you for opening an issue for this.
I haven't been able to reproduce it. I tested with the Spell Arena module which contains a pack of maps.

![image](https://github.com/SvenWerlen/moulinette-core/assets/938060/36d816bd-5c5f-4693-9354-2b206ddfc7da)

Did you re-index your scenes after upgrading to Foundry V11? Moulinette changed it's indexing process and you need to re-index assets. This might be your issue.

Otherwise, can you provide more information about your local modules?

**Comment by ktesterman007** [comment]
Okay I got it working :).  The issue was that I had some custom scenes in my config, and they kept making the indexer crash, so it never completed.  I just removed them, and now my modules have been indexed successfully.

Not sure why Moulinette keeps crashing on the custom ones though...

**Comment by SvenWerlen** [comment]
Good to know. Yes, if it happens that Moulinette crashes during indexing, nothing gets indexed. If you can reproduce it and provide a screenshot of the error, I'd like to fix this.
